---

version: '3'

env:
  OUT: caas-certificate-distribution-operator
  COV_FILE: cover.out
  ADO_COV_FILE: cover.xml
  ADO_TEST_FILE: "test-report.xml"
  SRC: ./cmd/main.go

tasks:
  default:
    cmds:
      - task: test
      - task: lint
      - task: generate-test-reports

  format:
    cmds:
      - go fmt ./...

  build:
    deps: [check-deps]
    cmds:
      - env GOOS=darwin GOARCH=amd64 go build -o {{.OUT}} {{.SRC}}
    sources:
      - ./cmd/*.go
      - ./api/*.go
      - ./internal/*.go
    generates:
      - ./{{.OUT}}

  test:
    deps: [build]
    cmds:
      # Skip utils package from coverage
      - go test $(go list ./... | grep -v api/ ) -race -v -coverprofile={{.COV_FILE}}

  lint:
    deps: [install-tools]
    cmds:
      - golangci-lint run --timeout=5m0s

  clean:
    cmds:
      - rm -f {{.OUT}} {{.COV_FILE}} {{.ADO_COV_FILE}} {{.ADO_TEST_FILE}}

  check-deps:
    cmds:
      - go mod tidy
      - go mod verify

  install-tools:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install gotest.tools/gotestsum@latest
      - go install github.com/axw/gocov/gocov@latest

  generate-test-reports:
    deps: [install-tools, test]
    cmds:
      - gotestsum --junitfile={{.ADO_TEST_FILE}}
      - gocov convert {{.COV_FILE}} | gocov-xml > {{.ADO_COV_FILE}}

  generate-html-coverage:
    deps: [install-tools, test]
    cmds:
      - go tool cover -html={{.COV_FILE}} -o coverage.html

  update-deps:
    cmds:
      - go get -u ./...
