
version: '3'

vars:
  GOPATH:
    sh: echo "$(go env GOPATH)" | sed 's/ /\\ /g' | sed 's/-/\\-/g'

tasks:
  build:
    deps: [linux-amd64]

  linux-amd64:
    desc: Build for Linux amd64
    cmds:
      - export CGO_ENABLED=0 GOOS=linux GOARCH=amd64 && go build -o handler-linux-amd64 cmd/main.go

  clean:
    cmds:
      - rm -f handler-* cover.out test-report.xml cover.xml

  install-tools:
    status:
      - test -f "{{.GOPATH}}/bin/gotestsum"
      - test -f "{{.GOPATH}}/bin/golangci-lint"
      - test -f "{{.GOPATH}}/bin/gocover-cobertura"
    cmds:
      - |
        go install gotest.tools/gotestsum@v1.12.0
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
          | sh -s -- -b "{{.GOPATH}}/bin" v2.1.6
        go get github.com/boumenot/gocover-cobertura


  test:
    deps: [install-tools]
    env:
      CGO_ENABLED: 1
      GO_ROOT: '{{.GO_ROOT}}'
    cmds:
      - |
        echo "Running tests..."
        gotestsum --junitfile=test-report.xml --format=testname \
          $(go list ./... ) \
          -v -race -coverprofile=cover.out
  lint:
    deps: [install-tools]
    cmds:
      - golangci-lint run --timeout=5m0s --tests=false

  generate-test-reports:
    deps: [test]
    cmds:
      - |
        gocover-cobertura < cover.out > cover.xml
