{{- if and .Values.caBundle.createSecret (typeIs "map" .Values.caBundle.createSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caBundle.createSecret.name | default (printf "%s-ca-bundle" (include "chart.fullname" .)) }}
  labels:
    app.kubernetes.io/component: ca-bundle
    app.kubernetes.io/created-by: caas-certificate-distribution-operator
    app.kubernetes.io/part-of: caas-certificate-distribution-operator
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{ .Values.caBundle.createSecret.key | default "ca.crt" }}: {{ .Values.caBundle.createSecret.value | default "" | b64enc | quote }}
{{- end -}}
