{{- if .Values.caBundle.secret.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caBundle.secret.name | default (printf "%s-ca-bundle" (include "chart.fullname" .)) }}
  labels:
    app.kubernetes.io/component: ca-bundle
    app.kubernetes.io/created-by: external-certificate-operator
    app.kubernetes.io/part-of: external-certificate-operator
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{ .Values.caBundle.secret.key | default "ca.crt" }}: {{ .Values.caBundle.secret.value | b64enc | quote }}
{{- end -}}
