apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}-ctrl-mgr-met-s
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: external-certificate-operator
    app.kubernetes.io/part-of: external-certificate-operator
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.type }}
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.metrics.ports | toYaml | nindent 2 }}
