apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: export-{{ include "chart.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: vexportcertificatesecret.kb.io
    clientConfig:
      {{- if .Values.caBundle.secret.value }}
      caBundle: {{ .Values.caBundle.secret.value | b64enc | quote }}
      {{- end }}
      service:
        name: {{ include "chart.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-external-certificate-operator-io-v1alpha1-exportcertificatesecret
    admissionReviewVersions:
      - v1
    failurePolicy: Fail
    rules:
      - apiGroups:
          - external-certificate.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - exportcertificatesecrets
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: import-{{ include "chart.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: vimportcertificatesecret.kb.io
    clientConfig:
      {{- if .Values.caBundle.secret.value }}
      caBundle: {{ .Values.caBundle.secret.value | b64enc | quote }}
      {{- end }}
      service:
        name: {{ include "chart.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-external-certificate-operator-io-v1alpha1-importcertificatesecret
    admissionReviewVersions:
      - v1
    failurePolicy: Fail
    rules:
      - apiGroups:
          - external-certificate.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - importcertificatesecrets
    sideEffects: None
