{{- if .Values.controllerManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: external-certificate-operator
    app.kubernetes.io/part-of: external-certificate-operator
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
{{- end }}
