# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foobar-cert
  namespace: foo-bar-ns
spec:
  isCA: true
  secretName: foobar-cert
  emailAddresses:
    - foo-bar@external-certificate.io
  privateKey:
    algorithm: RSA
    size: 4096
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "foo-bar.external-certificate.io"
  dnsNames:
  - "foo-bar.external-certificate.io"
  usages:
  - client auth
  - server auth
  additionalOutputFormats:
  - type: CombinedPEM
