# export.yaml
apiVersion: external-certificate.io/v1alpha1
kind: ExportCertificateSecret
metadata:
  name: export-crt-secret
  namespace: foo-bar-ns
spec:
  azurekv:
    vaultUrl: https://cdotestqa001cc-kv.vault.azure.net/
    serviceAccountRef:
      name: foo-bar-sa
    certificateSecretRef:
      - kvSecretName: foobar-tlscert          # Secret named to be named in AKV
        secretName: foobar-cert # Certificate spec.secretName
        secretKey: tls.crt
      - kvSecretName: foobar-tlskey           # Secret named to be named in AKV
        secretName: foobar-cert # Certificate spec.secretName
        secretKey: tls.key
