# CRDs are installed with sister chart external-certificate-operator-crd
apiVersion: v2
appVersion: 1.2.8
description: Helm chart for external-certificate-operator
name: certificate-distribution-op
type: application
version: 1.2.5
